### ISSUE TITLE
LayerUtility: JoyCaption2

### ISSUE THREAD

**Issue by 13426447442** [chflame163/ComfyUI_LayerStyle_Advance#12]
LayerUtility: JoyCaption2
local variable 'tokenizer' referenced before assignment

**Comment by Maelstrom2014** [comment]
the same ERROR : 
Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ai\comfyui\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance\py\joycaption_alpha_2.py", line 575, in load_joycaption2_model
    model = load_models(llm_model_path, dtype, vlm_lora, device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance\py\joycaption_alpha_2.py", line 170, in load_models
    return Joy2_Model(clip_processor, clip_model, tokenizer, text_model, image_adapter)
                                                  ^^^^^^^^^
UnboundLocalError: cannot access local variable 'tokenizer' where it is not associated with a value

**Comment by leekun123** [comment]
LayerUtility: JoyCaption2
cannot access local variable 'clip_model' where it is not associated with a value
