### ISSUE TITLE
使用LayerMask:PersonMaskUltra V2 (Advance) 节点时报错提示：动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by leeyuping92** [chflame163/ComfyUI_LayerStyle_Advance#9]
Traceback (most recent call last):
  File "C:\Users\lee\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lee\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lee\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\lee\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anzhuang\comfyui_desktop\ComfyUI\custom_nodes/ComfyUI_LayerStyle_Advance\py\person_mask_ultra_v2.py", line 73, in person_mask_ultra_v2
    import mediapipe as mp
  File "D:\anzhuang\comfyui_desktop\ComfyUI\.venv\Lib\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "D:\anzhuang\comfyui_desktop\ComfyUI\.venv\Lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import model_ckpt_util
ImportError: DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

**Comment by liuious** [comment]
解决了吗？我也出现同样的问题了

**Comment by planb788** [comment]
解决方法，找到python.exe所在目录，打开终端（确保当前路径为python.exe所在目录），输入python -m pip install msvc-runtime如果用的不是CMD这个终端，而是powershell，那就输入.\python -m pip install msvc-runtime
